// Generated by CoffeeScript 2.3.2
(function() {
  var CoinsDaily;

  this.o.ViewCoinsDaily = CoinsDaily = (function() {
    class CoinsDaily extends this.o.View {
      remove() {
        clearTimeout(this._left_timeout);
        return super.remove(...arguments);
      }

    };

    CoinsDaily.prototype.className = 'coins-daily';

    CoinsDaily.prototype.template = "<span> &=left </span>";

    CoinsDaily.prototype.options_default = {
      left: null
    };

    CoinsDaily.prototype.options_html = {
      left: function(v) {
        if (v === null) {
          return '';
        }
        if (v === 0) {
          return `${_l('coinsdaily.daily')} <button>${_l('coinsdaily.get')} <span>${this.options.coins}</span></button>`;
        }
        return `${_l('coinsdaily.daily')} ${_l('coinsdaily.after')} ` + [60 * 60, 60, 1].map((seconds) => {
          var units;
          if (seconds === 1) {
            return v;
          }
          units = Math.floor(v / seconds);
          v = v - units * seconds;
          return units;
        }).map(function(v) {
          if (v < 10) {
            return `0${v}`;
          } else {
            return v;
          }
        }).join(':');
      }
    };

    CoinsDaily.prototype.options_bind = {
      left: function() {
        clearTimeout(this._left_timeout);
        if (this.options.left && this.options.left > 0) {
          return this._left_timeout = setTimeout(() => {
            return this.options_update({
              left: this.options.left - 1
            });
          }, 1000);
        }
      }
    };

    CoinsDaily.prototype.events = {
      'click button': function() {
        return this.trigger('get');
      }
    };

    return CoinsDaily;

  }).call(this);

}).call(this);
