// Generated by CoffeeScript 2.3.2
(function() {
  var Sound;

  this.o.Sound = Sound = class Sound {
    constructor(options) {
      this.options = options;
    }

    play(sound) {
      var a;
      try {
        a = new Audio(`${this.options.path}${sound}.wav`);
        a.volume = 0.3;
        return a.play();
      } catch (error) {

      }
    }

  };

}).call(this);
