// Generated by CoffeeScript 2.3.2
(function() {
  var AnalyticCordova;

  window.o.AnalyticCordova = AnalyticCordova = class AnalyticCordova {
    init() {
      return window.ga.startTrackerWithId(App.config.google_analytics);
    }

    config(params = {}) {
      window.ga.setUserId(params.user_id);
      return window.ga.setAppVersion(App.version);
    }

    screen(screen_name) {
      return window.ga.trackView(`${screen_name} ${App.lang}`);
    }

    exception(description) {
      return window.ga.trackException(description, false);
    }

    buy_start(params) {}

    buy_complete(params) {}

  };

}).call(this);
