// Generated by CoffeeScript 2.7.0
(function() {
  var AnalyticFirebase;

  window.o.Analytic = AnalyticFirebase = class AnalyticFirebase {
    init({firebase_config}) {
      firebase.initializeApp(firebase_config);
      return firebase.analytics();
    }

    config(params = {}) {
      firebase.analytics().setUserId(`${params.user_id}`);
      return this.user_property({
        'Language': App.lang
      });
    }

    user_property(params = {}) {
      return firebase.analytics().setUserProperties(params);
    }

    screen(view) {
      return firebase.analytics().setCurrentScreen(view);
    }

    exception({msg, url, line, column, user_agent}) {
      return this.event('JS Error', {msg, url, line, column, user_agent});
    }

    // firebase.analytics().logEvent('exception', params);
    buy_start(params) {}

    buy_complete(params) {}

    event(event, params) {
      return firebase.analytics().logEvent(event, params);
    }

  };

}).call(this);
