// Generated by CoffeeScript 2.4.1
(function() {
  var Popup, PopupAuthorize;

  Popup = window.o.ViewPopup;

  window.o.ViewPopupAuthorize = PopupAuthorize = (function() {
    class PopupAuthorize extends Popup {};

    PopupAuthorize.prototype.className = Popup.prototype.className + '-authorize';

    PopupAuthorize.prototype.options_default = {
      close: false,
      head: _.template("<%= _l('Authorize.head') %>"),
      body: _.template("<p>\n  <% self.options.platforms.forEach(function (platform) { %>\n\n    <button data-click='authorize' data-click-attr='<%= platform %>' class='<%= self.className %>-<%= platform %>'><%= platform %></button>\n  <% }) %>\n</p>\n<p>\n  <%= _l('Authorize.desc') %>\n</p>")
    };

    return PopupAuthorize;

  }).call(this);

}).call(this);
