// Generated by CoffeeScript 2.7.0
(function() {
  var Popup, PopupAuthorize;

  Popup = window.o.ViewPopup;

  window.o.ViewPopupAuthorize = PopupAuthorize = (function() {
    class PopupAuthorize extends Popup {};

    PopupAuthorize.prototype.className = Popup.prototype.className + '-authorize';

    PopupAuthorize.prototype.options_default = {
      close: false,
      head: _.template(`<%= _l('Authorize.head') %>`),
      body: _.template(`<p class='&-legal'>
  <%= _l('Authorize.legal.head', {
    terms: '<a target="_blank" href="'+ (typeof App.config.legal.terms === 'function' ? App.config.legal.terms() : App.config.legal.terms ) +'">' + _l('Authorize.legal.terms') + '</a>',
    privacy: '<a target="_blank" href="'+ (typeof App.config.legal.privacy === 'function' ? App.config.legal.privacy() : App.config.legal.privacy ) +'">' + _l('Authorize.legal.privacy') + '</a>'
  }) %>
</p>
<div class='&-buttons' data-lang='<%= App.lang %>'>
  <% self.options.platforms.forEach(function (platform) { %>

    <button data-click='authorize' <%= (['google', 'apple'].indexOf(platform) >= 0 ? '' : ' data-hidden' ) %> data-click-attr='<%= platform %>'></button>
  <% }) %>
  <button data-more></button>
</div>
<p>
  <%= _l('Authorize.desc') %>
</p>`)
    };

    PopupAuthorize.prototype.events = Object.assign({}, Popup.prototype.events, {
      'click button[data-more]': function() {
        this.$('[data-click="authorize"][data-hidden]').removeAttr('data-hidden');
        return this.$('button[data-more]').attr('data-hidden', '');
      }
    });

    return PopupAuthorize;

  }).call(this);

}).call(this);
