// Generated by CoffeeScript 2.5.1
(function() {
  var Popup, PopupAuthorize;

  Popup = window.o.ViewPopup;

  window.o.ViewPopupIframe = PopupAuthorize = (function() {
    class PopupAuthorize extends Popup {};

    PopupAuthorize.prototype.className = Popup.prototype.className + '-iframe';

    PopupAuthorize.prototype.options_default = {
      close: true,
      body: _.template(`<iframe frameborder='0' src='<%= self.options.link %>' style='width:100%;height:100%;'>`)
    };

    return PopupAuthorize;

  }).call(this);

}).call(this);
