// Generated by CoffeeScript 2.3.2
(function() {
  var Common;

  window.o.PlatformCommon = Common = class Common {
    language_check(callback) {
      if (!window._locales_default) {
        return callback();
      }
      return this.router.subview_append(new window.o.ViewPopupLanguage()).bind('language', (language) => {
        App.lang = language;
        return this.router.render();
      }).bind('remove', () => {
        return callback();
      }).render().$el.appendTo(this.router.$el);
    }

    connect(params) {
      return window.o.Connector(Object.assign({
        router: this.router,
        address: App.config.server,
        version: document.body.getAttribute('data-version'),
        version_callback: () => {
          return this.router.message(_l('version error'));
        }
      }, params));
    }

    auth_send(p) {
      this.router.message(_l('Authorizing'));
      return this.router.send('authenticate:try', p);
    }

  };

}).call(this);
