// Generated by CoffeeScript 2.5.1
(function() {
  var Common;

  window.o.PlatformCommon = Common = class Common {
    constructor(options) {
      this.options = options;
      this.router = new window.o.Router(Object.assign({
        platform: this.options.platform
      }, this.options.router));
      this.router.$el.appendTo('body');
    }

    language_check(callback) {
      if (!window._locales_default) {
        return callback();
      }
      return this.router.subview_append(new window.o.ViewPopupLanguage()).bind('language', (language) => {
        return this._language_update(language);
      }).bind('remove', () => {
        return callback();
      }).render().$el.appendTo(this.router.$el);
    }

    _auto_login() {
      if (!this.auth()) {
        if (this.options.anonymous) {
          return this.router.trigger('anonymous');
        }
        if (!this.options.language_check) {
          return this.auth_popup();
        }
        return this.language_check(() => {
          return this.auth_popup();
        });
      }
    }

    connect(params) {
      return window.o.Connector(Object.assign({
        router: this.router,
        address: App.config.server,
        version: App.version,
        version_callback: () => {
          return this.router.message({
            body: _l('Authorize.version error'),
            actions: [
              {
                'reload': _l('Authorize.button.reload')
              }
            ]
          });
        }
      }, params));
    }

    _language_update(language) {
      App.lang = language;
      return this._language_set = true;
    }

    buy(params, name = null) {
      return this.router.send(`buy:${name || this._name}`, Object.assign({
        language: App.lang
      }, params));
    }

    auth_send(p) {
      this.router.message(_l('Authorize.Authorizing'));
      return this.router.send('authenticate:try', Object.assign({
        platform: this.options.platform
      }, this._language_set ? {
        language: App.lang
      } : void 0, p));
    }

  };

}).call(this);
