// Generated by CoffeeScript 2.7.0
(function() {
  window.Cookies = {
    set: function(key, value) {
      var e;
      try {
        return window.localStorage.setItem(key, value);
      } catch (error) {
        e = error;
        return null;
      }
    },
    get: function(key) {
      var e;
      try {
        return window.localStorage.getItem(key);
      } catch (error) {
        e = error;
        return null;
      }
    }
  };

}).call(this);
