// Generated by CoffeeScript 2.7.0
(function() {
  var Draugiem;

  window.o.PlatformDraugiem = Draugiem = (function() {
    class Draugiem extends window.o.PlatformCommon {
      constructor() {
        var fn;
        super(...arguments);
        fn = (event, data) => {
          if (event === 'authenticate:error') {
            this.router.message(_l('Authorize.integrated login error'));
          }
          if (event === 'authenticate:success') {
            return this.router.unbind('request', fn);
          }
        };
        this.router.bind('request', fn);
        this.router.bind('connect', () => {
          return this.auth_send({
            draugiem: this.router._get('dr_auth_code')
          });
        });
        this.router.bind(`request:buy:${this._name}`, ({link}) => {
          return window.draugiemWindowOpen(link, 350, 400);
        });
        this.__init();
        this;
      }

      __init() {
        window.draugiem_callback_url = location.protocol + '//' + document.domain + '/draugiem-callback.html';
        window.draugiem_domain = this.router._get('domain');
        return $('<script>').attr({
          'src': '//ifrype.com/applications/external/draugiem.js'
        }).appendTo(document.body);
      }

      invite(text) {
        return draugiemSendInvite(text);
      }

      share({text, title, prefix, link}, callback = function() {}) {
        return draugiemSay(title, link, prefix, text, function(success) {
          if (success) {
            return callback();
          }
        });
      }

    };

    Draugiem.prototype._name = 'draugiem';

    return Draugiem;

  }).call(this);

}).call(this);
