// Generated by CoffeeScript 2.7.0
(function() {
  var Fbinstant;

  window.o.PlatformFbinstant = Fbinstant = (function() {
    class Fbinstant extends window.o.PlatformCommon {
      constructor(options) {
        var fn;
        super(...arguments);
        this.options = options;
        fn = (event, data) => {
          if (event === 'authenticate:error') {
            this.auth_error();
          }
          if (event === 'authenticate:success') {
            this.router.unbind('request', fn);
            if (this.options.payments) {
              return FBInstant.payments.onReady(() => {
                this._get_catalog();
                return this._get_payments();
              });
            }
          }
        };
        this.router.bind('request', fn);
        this.router.bind('connect', () => {
          return this.auth_send({
            'facebook': 'fbinstant:' + this._fbinstant_signature,
            language: FBInstant.getLocale()
          });
        });
        this.router.bind(`request:buy:${this._name}`, ({service, transaction_id}) => {
          var productID;
          productID = this.options.payments && this.options.payments[service];
          if (!productID) {
            return;
          }
          return FBInstant.payments.purchaseAsync({
            productID,
            developerPayload: `${transaction_id}`
          }).then((purchase) => {
            return this._payment_validate(purchase);
          }).catch(function(err) {
            return console.error('FBInstant.payments.purchaseAsync error', err);
          });
        });
        this.router.bind(`request:buy:${this._name}:validate`, ({id_local}) => {
          return FBInstant.payments.consumePurchaseAsync(id_local);
        });
        this;
      }

      _get_catalog() {
        if (!this.options.payments_ready) {
          return;
        }
        return FBInstant.payments.getCatalogAsync().then((products) => {
          var services;
          // per-service, not an inverted productID->service map: multiple services (e.g. vip/vipyear
          // tiers) can share the same product ID, which a simple inversion would silently collapse
          services = Object.keys(this.options.payments).map((service) => {
            var product, productID;
            productID = this.options.payments[service];
            product = products.find(function(p) {
              return p.productID === productID;
            });
            if (!product) {
              return;
            }
            return {
              service,
              price_str: product.price
            };
          });
          return this.options.payments_ready(services.filter(function(v) {
            return v;
          }));
        });
      }

      _get_payments() {
        return FBInstant.payments.getPurchasesAsync().then((purchases) => {
          return purchases.forEach((purchase) => {
            return this._payment_validate(purchase);
          });
        });
      }

      _payment_validate(purchase) {
        return this._queue_success(() => {
          return this.router.send(`buy:${this._name}:validate`, {
            signature: purchase.signedRequest,
            id_local: purchase.purchaseToken
          });
        });
      }

      // notification_enable: (callback)->
      //   FBInstant.player.canSubscribeBotAsync().then (can_subscribe)=>
      //     callback can_subscribe
      //   .catch =>
      //     callback false

        // notification_ask: (callback)->
      //   FBInstant.player.subscribeBotAsync().then =>
      //     callback true
      //   .catch =>
      //     callback false
      init(assets, callback) {
        var loaded, start;
        loaded = 0;
        start = () => {
          if (loaded < assets.length) {
            FBInstant.setLoadingProgress(loaded * 100 / assets.length);
            return;
          }
          return FBInstant.startGameAsync().then(() => {
            return FBInstant.player.getSignedPlayerInfoAsync().then((result) => {
              this._fbinstant_signature = result.getSignature();
              return callback();
            });
          });
        };
        return $('<script>').attr({
          'src': 'https://connect.facebook.net/en_US/fbinstant.8.0.js',
          'id': 'facebook-jssdk'
        }).on('load', () => {
          return FBInstant.initializeAsync().then(() => {
            if (assets.length === 0) {
              return start();
            }
            return assets.forEach(function(src) {
              var i;
              i = new Image();
              i.onload = function() {
                loaded++;
                return start();
              };
              i.src = src;
              return start();
            });
          });
        }).appendTo(document.body);
      }

      // invite: (params = {}, callback=->)->
      //   FBInstant.shareAsync Object.assign( {intent: 'INVITE', image: '', text: ''}, params )
      //   .then =>
      //     callback()

        // share: (params = {}, callback=->)->
      //   FBInstant.shareAsync Object.assign( {intent: 'SHARE', image: '', text: ''}, params )
      //   .then =>
      //     callback()
      auth_error() {
        return this.router.message({
          body: _l('Authorize.integrated login error'),
          actions: [
            {
              'reload': _l('Authorize.button.reload')
            }
          ]
        });
      }

    };

    Fbinstant.prototype._name = 'fbinstant';

    return Fbinstant;

  }).call(this);

}).call(this);
