// Generated by CoffeeScript 2.7.0
(function() {
  var Fbinstant;

  window.o.PlatformFbinstant = Fbinstant = (function() {
    class Fbinstant extends window.o.PlatformCommon {
      constructor(options) {
        var fn;
        super(...arguments);
        this.options = options;
        fn = (event, data) => {
          if (event === 'authenticate:error') {
            this.auth_error();
          }
          if (event === 'authenticate:success') {
            return this.router.unbind('request', fn);
          }
        };
        this.router.bind('request', fn);
        this.router.bind('connect', () => {
          return FBInstant.player.getSignedPlayerInfoAsync().then((result) => {
            return this.auth_send({
              'facebook': 'fbinstant:' + result.getSignature(),
              language: FBInstant.getLocale()
            });
          });
        });
        // @router.bind "request:buy:#{@_name}", ({service, id})=>
        // subscription = App.config.buy.subscription and service in Object.keys(App.config.buy.subscription)
        // window.FB.ui {
        //   method: 'pay'
        //   action: if subscription then 'create_subscription' else 'purchaseitem'
        //   product: "#{App.config.server}/d/og/service-#{service}-#{App.lang}.html"
        //   request_id: id
        // }, ->
        // {subscription_id: 348322315297870, status: "active"}
        this;
      }

      // subscription_action: ({action, subscription_id})->
      // action: 'reactivate_subscription', 'cancel_subscription', 'modify_subscription'
      // window.FB.ui {
      //   method: 'pay'
      //   action
      //   subscription_id
      // }, ->

        // notification_enable: (callback)->
      //   FBInstant.player.canSubscribeBotAsync().then (can_subscribe)=>
      //     callback can_subscribe
      //   .catch =>
      //     callback false

        // notification_ask: (callback)->
      //   FBInstant.player.subscribeBotAsync().then =>
      //     callback true
      //   .catch =>
      //     callback false
      init(assets, callback) {
        var loaded, start;
        loaded = 0;
        start = () => {
          if (loaded < assets.length) {
            FBInstant.setLoadingProgress(loaded * 100 / assets.length);
            return;
          }
          return FBInstant.startGameAsync().then(() => {
            return callback();
          });
        };
        return $('<script>').attr({
          'src': 'https://connect.facebook.net/en_US/fbinstant.8.0.js',
          'id': 'facebook-jssdk'
        }).on('load', () => {
          return FBInstant.initializeAsync().then(() => {
            if (assets.length === 0) {
              return start();
            }
            return assets.forEach(function(src) {
              var i;
              i = new Image();
              i.onload = function() {
                loaded++;
                return start();
              };
              i.src = src;
              return start();
            });
          });
        }).appendTo(document.body);
      }

      // invite: (params = {}, callback=->)->
      //   FBInstant.shareAsync Object.assign( {intent: 'INVITE', image: '', text: ''}, params )
      //   .then =>
      //     callback()

        // share: (params = {}, callback=->)->
      //   FBInstant.shareAsync Object.assign( {intent: 'SHARE', image: '', text: ''}, params )
      //   .then =>
      //     callback()
      auth_error() {
        return this.router.message({
          body: _l('Authorize.integrated login error'),
          actions: [
            {
              'reload': _l('Authorize.button.reload')
            }
          ]
        });
      }

    };

    Fbinstant.prototype._name = 'facebook';

    return Fbinstant;

  }).call(this);

}).call(this);
