// Generated by CoffeeScript 2.4.1
(function() {
  var Inbox;

  window.o.PlatformInbox = Inbox = class Inbox extends window.o.PlatformCommon {
    constructor() {
      var fn;
      super();
      this.router = new window.o.Router();
      this.router.$el.appendTo('body');
      fn = (event, data) => {
        if (event === 'authenticate:error') {
          this.router.message(_l('Authorize.integrated login error'));
        }
        if (event === 'authenticate:success') {
          return this.router.unbind('request', fn);
        }
      };
      this.router.bind('request', fn);
      this.router.bind('connect', () => {
        return this.auth_send({
          inbox: this.router._get('uid'),
          language: this.router._get('language')
        });
      });
      this.router.bind('request:buy:inbox:response', ({link}) => {
        return this.router.subview_append(new window.o.ViewPopupIframe({
          link,
          parent: this.router.$el
        }).render());
      });
      this;
    }

  };

}).call(this);
