// Generated by CoffeeScript 2.5.1
(function() {
  var Inbox;

  window.o.PlatformInbox = Inbox = (function() {
    class Inbox extends window.o.PlatformCommon {
      constructor() {
        var fn;
        super(...arguments);
        fn = (event, data) => {
          if (event === 'authenticate:error') {
            this.router.message(_l('Authorize.integrated login error'));
          }
          if (event === 'authenticate:success') {
            return this.router.unbind('request', fn);
          }
        };
        this.router.bind('request', fn);
        this.router.bind('connect', () => {
          return this.auth_send({
            inbox: this.router._get('uid'),
            language: this.router._get('language')
          });
        });
        this.router.bind(`request:buy:${this._name}`, ({link}) => {
          return this.router.subview_append(new window.o.ViewPopupIframe({
            link,
            parent: this.router.$el
          }).render());
        });
        this;
      }

    };

    Inbox.prototype._name = 'inbox';

    return Inbox;

  }).call(this);

}).call(this);
