// Generated by CoffeeScript 2.3.2
(function() {
  var Inbox;

  window.o.PlatformInbox = Inbox = class Inbox {
    constructor() {
      var fn;
      this.router = new window.o.Router();
      this.router.$el.appendTo('body');
      fn = (event, data) => {
        if (event === 'authenticate:error') {
          this.router.message(_l('integrated login error'));
        }
        if (event === 'authenticate:success') {
          return this.router.unbind('request', fn);
        }
      };
      this.router.bind('request', fn);
      this.router.bind('connect', () => {
        return this.router.send('authenticate:try', {
          inbox: this.router._get('uid'),
          language: this.router._get('language')
        });
      });
      this.router.bind('request:buy:inbox:response', ({link}) => {
        return this.router.subview_append(new window.o.ViewPopupIframe({
          link,
          parent: this.router.$el
        }).render());
      });
      this;
    }

    connect() {
      return window.o.Connector({
        router: this.router,
        address: '',
        version: document.body.getAttribute('data-version'),
        version_callback: () => {
          return this.router.message(_l('version error'));
        }
      });
    }

  };

}).call(this);
