// Generated by CoffeeScript 2.5.1
(function() {
  var Odnoklassniki;

  window.o.PlatformOdnoklassniki = Odnoklassniki = (function() {
    class Odnoklassniki extends window.o.PlatformCommon {
      constructor() {
        var fn;
        super(...arguments);
        fn = (event, data) => {
          if (event === 'authenticate:error') {
            this.router.message(_l('Authorize.integrated login error'));
          }
          if (event === 'authenticate:success') {
            return this.router.unbind('request', fn);
          }
        };
        this.router.bind('request', fn);
        this.router.bind('connect', () => {
          return this.auth_send({
            odnoklassniki: window.location.href.split('?')[1],
            language: 'ru'
          });
        });
        this;
      }

    };

    Odnoklassniki.prototype._name = 'odnoklassniki';

    return Odnoklassniki;

  }).call(this);

}).call(this);
