// Generated by CoffeeScript 2.7.0
(function() {
  var Vkontakte;

  window.o.PlatformVkontakte = Vkontakte = (function() {
    class Vkontakte extends window.o.PlatformCommon {
      constructor() {
        var fn;
        super(...arguments);
        fn = (event, data) => {
          if (event === 'authenticate:error') {
            this.router.message(_l('Authorize.integrated login error'));
          }
          if (event === 'authenticate:success') {
            return this.router.unbind('request', fn);
          }
        };
        this.router.bind('request', fn);
        this.router.bind('connect', () => {
          return this.auth_send({
            vkontakte: window.location.href.split('?')[1],
            language: this.router._get('language') === '3' ? 'en' : 'ru'
          });
        });
        this;
      }

      __init(callback) {
        var script;
        script = document.createElement('script');
        script.onload = function() {
          vkBridge.send('VKWebAppInit');
          return callback();
        };
        script.src = '//unpkg.com/@vkontakte/vk-bridge/dist/browser.min.js';
        return document.head.appendChild(script);
      }

      invite() {
        return vkBridge.send("VKWebAppShowInviteBox", {});
      }

      share({link}) {
        return vkBridge.send("VKWebAppShare", {link});
      }

    };

    Vkontakte.prototype._name = 'vkontakte';

    return Vkontakte;

  }).call(this);

}).call(this);
