// Generated by CoffeeScript 2.5.1
(function() {
  var Yandex;

  window.o.PlatformYandex = Yandex = (function() {
    class Yandex extends window.o.PlatformCommon {
      constructor() {
        var fn;
        super(...arguments);
        fn = (event, data) => {
          if (event === 'authenticate:error') {
            this.auth_error();
          }
          if (event === 'authenticate:success') {
            return this.router.unbind('request', fn);
          }
        };
        this.router.bind('request', fn);
        this.router.bind('connect', () => {});
        // @router.bind "request:buy:#{@_name}", ({service, transaction_id, price})=>
        //   FAPI.UI.showPayment(
        //     params.name,
        //     params.description,
        //     params.code,
        //     price,
        //     null,
        //     JSON.stringify({transaction_id}),
        //     'ok',
        //     true
        //   )
        this;
      }

      _get_user(callback = function() {}, callback_error = function() {}) {
        // ysdk.getPlayer({signed: true, scope: true}).then(function(player){ console.info(player) }).catch( function () { console.info('not authorized') } )
        this.auth_send({
          yandex: 'O3SAuJAq/PLFHNCFb3/vZLyQbNHA3lIIzoTN8OtCalY=.eyJhbGdvcml0aG0iOiJITUFDLVNIQTI1NiIsImlzc3VlZEF0IjoxNjI3NDc2NzQ5LCJyZXF1ZXN0UGF5bG9hZCI6IiIsImRhdGEiOnsiaWQiOiJNbFduc2JYNVV3N0MzRW50YlNPYWNYZ3UvcDNGYWpLT21PMFV5U2FWczFNPSIsInVuaXF1ZUlEIjoiTWxXbnNiWDVVdzdDM0VudGJTT2FjWGd1L3AzRmFqS09tTzBVeVNhVnMxTT0iLCJsYW5nIjoiZW4iLCJwdWJsaWNOYW1lIjoiVmFsZXJ5IiwiYXZhdGFySWRIYXNoIjoiSTY2RjU3SldRTFVSRjZITTMySEU2R1lVSTJJM0RQSVA1WFZaTzdOT1c0NUhZNDVPSDZOVkpCUEdKTjY3NTJWRzNGWVBIRzYyRFpKV1ZUTldZTEhGVEdTWEU3RVBCRTNKSElPNFdHWUE2SjJPRUtJVFEyWldNUDZKQTdLRjVWSUlZR1pKUE1BN0ozUE9STkxYNjQyV01ZWE8iLCJzY29wZVBlcm1pc3Npb25zIjp7ImF2YXRhciI6ImFsbG93IiwicHVibGljX25hbWUiOiJhbGxvdyJ9fX0='
        });
        callback();
        return;
        return ysdk.getPlayer({
          signed: true,
          scope: true
        }).then((player) => {
          this.auth_send({
            yandex: player.signature
          });
          return callback();
        }).catch(() => {
          return callback_error();
        });
      }

      auth() {
        return this._get_user(function() {}, () => {
          return ysdk.auth.openAuthDialog().then(() => {
            return this.auth();
          }).catch(() => {});
        });
      }

      __init(callback) {
        var script;
        script = document.createElement('script');
        script.async = true;
        script.onload = () => {
          return YaGames.init().then((ysdk) => {
            window.ysdk = ysdk;
            callback();
            return this._get_user(function() {}, () => {
              return this.router.trigger('anonymous');
            });
          });
        };
        script.src = 'https://yandex.ru/games/sdk/v2';
        return document.head.appendChild(script);
      }

      auth_error() {
        return this.router.message({
          close: true,
          body: _l('Authorize.integrated login error')
        }).bind('close', () => {
          return this.router.trigger('anonymous');
        });
      }

    };

    Yandex.prototype._name = 'yandex';

    return Yandex;

  }).call(this);

}).call(this);
